### ISSUE TITLE
Error while testing in the console

### ISSUE THREAD

**Issue by shan02** [alexa/skill-sample-node-device-address-api#1]
Hello,

I was trying the step by step guide and seeing this error in the cloud watch log

START RequestId: fd54997b-1d92-11e7-b48a-8576f9805fab Version: $LATEST
2017-04-10T02:11:21.756Z	fd54997b-1d92-11e7-b48a-8576f9805fab	Beginning execution for skill with APP_ID={**My skill id**}
2017-04-10T02:11:21.815Z	fd54997b-1d92-11e7-b48a-8576f9805fab	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:103:38)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:92:31)
    at exports.handler (/var/task/index.js:19:11)
END RequestId: fd54997b-1d92-11e7-b48a-8576f9805fab
REPORT RequestId: fd54997b-1d92-11e7-b48a-8576f9805fab	Duration: 140.25 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 24 MB	
RequestId: fd54997b-1d92-11e7-b48a-8576f9805fab Process exited before completing request

Any idea, why this would happen?

**Comment by muttoni** [comment]
How are you testing? Are you using an actual Alexa JSON response object as your test case?

**Comment by shan02** [comment]
I am testing it through the online Service Simulator by sending in sample JSON request. Here is the request

{
  "session": {
    "sessionId": "SessionId.5d6b0656-b318-4a85-807f-43cd42a296e7",
    "application": {
      "applicationId": "<APP_ID>"
    },
    "attributes": {},
    "user": {
      "userId": "<USER_ID>"    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.1fd101a4-0e89-4136-b446-c6a13219f00b",
    "locale": "en-US",
    "timestamp": "2017-04-20T13:19:17Z",
    "intent": {
      "name": "GetAddress where i live",
      "slots": {}
    }
  },
  "version": "1.0"
}

NOTE:
Error what i have posted in the beginning of this thread is from console.awazon.com, where i have uploaded the source code and testing it from the console itself.

Suda

**Comment by ghost** [comment]
@shan02 Any idea why the request doesn't have the device id? It should have the device id right?

**Comment by Jake8K** [comment]
I'm also trying to use the device ID for zip code, I'm failing on your skill (and mine) with the following request:
{
  "session": {
    "sessionId": "SessionId.5f54b59e-6e73-48d3-9865-f6fc43b31245",
    "application": {
      "applicationId": "amzn1.ask.skill.05cdeb90-4bc5-42ce-8d61-ed5912b658c5"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AHBJ4HM6AQWEYG2DLDBXNKDL4EFNLZCDKFO4G6N2RVO2472MG653SWWHYR2ASOB7EVQXVOFUK7OJFHMCVM4QMEFFRREE77DKWBOAJR2ZAGVDP6KXSHYECST562YR6NHRAC6QWCSEXHOX3HH4IMAEDCCKU5GDPBGJ6ZXM7OEX6GP4ZRMFYXQ5I3TTM4YTA6BRUJQXE3ONDSSM6GA"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.d420c64b-a826-44ab-9f7e-354c628cabac",
    "locale": "en-US",
    "timestamp": "2017-06-23T21:23:52Z",
    "intent": {
      "name": "GetAddress",
      "slots": {}
    }
  },
  "version": "1.0"
}

This is the Lambda response (fail)"
{
  "errorMessage": "Cannot read property 'System' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.getAddressHandler (/var/task/src/Handlers.js:59:44)",
    "emitNone (events.js:86:13)",
    "AlexaRequestEmitter.emit (events.js:185:7)",
    "Object.newSessionRequestHandler (/var/task/src/Handlers.js:36:14)",
    "emitNone (events.js:86:13)",
    "AlexaRequestEmitter.emit (events.js:185:7)",
    "AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:143:10)",
    "AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:110:23)",
    "AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:72:31)",
    "exports.handler (/var/task/src/index.js:19:11)"
  ]
}

Our code has the same point of failure: 
const consentToken = this.event.context.System.user.permissions.consentToken;
( or const deviceId = this.event.context.System.device.deviceId; if I switch things up)

Any idea why that System object would be uninitialized? I can't find any documentation for it

**Comment by dsbaha** [comment]
Hi, I ran into this earlier today with my skills being rejected.  I came to the following conclusion;

`
    var consentToken;
    var deviceId;
    var apiEndpoint;

    try {
        consentToken = this.event.context.System.user.permissions.consentToken;
        deviceId = this.event.context.System.device.deviceId;
        apiEndpoint = this.event.context.System.apiEndpoint;

        if(!consentToken || !deviceId || !apiEndpoint) {
            throw("User did not give us permissions to access their address.");
        }
        
    } catch(e) {
        this.emit(":tellWithPermissionCard", Messages.NOTIFY_MISSING_PERMISSIONS, PERMISSIONS);
        // Lets terminate early since we can't do anything else.
        console.log(JSON.stringify(this.event));
        console.error(e);
        console.info("Ending getAddressHandler()");
        return;
    }
`

**Comment by franklin-lobb** [comment]
Looks like this may have been resolved, so closing this issue due to inactivity.
